print("Hello World!")
print("This is going to be fun.")
print("She told me, \"You are a good friend.\"")
print("\nPoem:")
print("\n\t\tTwinkle, Twinkle \nTwinkle, twinkle little star,\nHow I wonder what you are.\n\t\tUp above the world so high,\n\t\tLike a diamond in the sky.")